### PR TITLE
Rewrite With New Features

### PR DESCRIPTION
**Pull request by SmushyTaco**
1. Updated all dependencies to their latest versions so there are no vulnerabilities or deprecations.
2. Swapped out "upath" with the more actively maintained "pathe"
3. Completely rewritten in strict TypeScript for better maintainability.
4. Added --patch (-p) to target specific packages to patch.
5. Added --reverse (-r) to reverse patches on all (or on specific) packages.
6. Updated the README.md to showcase these new features.
7. Added prettier and eslint to ensure good code quality.

### CODE REVIEW

**Comment by tmcdos** [comment]
Thank you very much for your effort and desire to improve this tool. This is exactly the spirit of open-source!
I appreciate what you have done but I still want to express my opinion. It may sound strange but I strongly prefer JSdoc over TypeScript. And while I do love ESLint - I very much dislike Prettier.
Since I don't want to ask you to rewrite your PR just to satisfy my personal preference (like many other maintainers require before accepting a PR - and I don't really like such an attitude) - I am going to apply the suggested improvements manually while still excluding TypeScript and Prettier. I hope you won't be upset too much by my decision :)
Thank you again for your contribution!

**Comment by SmushyTaco** [comment]
I'm not upset I completely understand! Thank you for being so receptive to my changes and taking the initiative to make your preferred changes yourself, that's pretty rare in the open source world so I really appreciate that.

I do have an alternative proposal that may interest you, if you'd like, I could maintain the project for you going forward instead which means we could keep the advantages of TypeScript. It puts less work on you and makes future maintenance for the project easier. If you'd still prefer to maintain the project yourself I completely understand but my offer stays on the table. Thank you once again!

**Comment by SmushyTaco** [comment]
I've gone ahead and released my fork on the NPM registry. I believe TypeScript will be better for the long term maintenance of the project and I don't want this to be restricted to what can be ran on Windows 7 either. Feel free to port my changes over regardless but I'll still be maintaining my own fork for these design differences, I hope you understand. Thanks.

**Comment by tmcdos** [comment]
I totally understand. Sorry for the delay, I am too busy at work and did not have the chance to spend some time on the project.
I am totally okay if you continue to maintain your fork and add new features.
I am scratching my own itch here so I still need to keep Win7 compatibility. I would definitely port your changes as soon as I get some free time!

**Pull request closed without merging**
